# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yldt_braintree', '0003_auto_20150621_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='braintreetransaction',
            name='payment_method_nonce',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='braintreetransaction',
            name='payment_method_token',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
