# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRejectedEvent',
            fields=[
                ('baseevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaigns.BaseEvent')),
            ],
            options={
                'abstract': False,
            },
            bases=('campaigns.baseevent',),
        ),
        migrations.CreateModel(
            name='ProcessPaymentEvent',
            fields=[
                ('baseevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaigns.BaseEvent')),
            ],
            options={
                'abstract': False,
            },
            bases=('campaigns.baseevent',),
        ),
        migrations.CreateModel(
            name='UnverifyPaymentEvent',
            fields=[
                ('baseevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaigns.BaseEvent')),
            ],
            options={
                'abstract': False,
            },
            bases=('campaigns.baseevent',),
        ),
        migrations.CreateModel(
            name='VerifyPaymentEvent',
            fields=[
                ('baseevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaigns.BaseEvent')),
            ],
            options={
                'abstract': False,
            },
            bases=('campaigns.baseevent',),
        ),
        migrations.RenameModel(
            old_name='BeginPaymentEvent',
            new_name='PledgePaymentEvent',
        ),
        migrations.AddField(
            model_name='transaction',
            name='last_rejected',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='times_rejected',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.IntegerField(choices=[(0, 'pledged'), (30, 'unverified'), (60, 'verified'), (100, 'payment processing'), (200, 'complete'), (500, 'aborted')]),
        ),
    ]
