# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_auto_20160419_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
